### ISSUE TITLE
Aliyun error: argument provider_name: invalid choice: 'null'

### ISSUE THREAD

**Issue by dxh000130** [troykelly/hassio-addons-letsencrypt-lexicon#40]
Got error: argument provider_name: invalid choice: 'null'
![屏幕截图 2024-01-16 094411](https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/assets/34475380/e546aa1e-e747-426b-9c23-2843248af3db)

![屏幕截图 2024-01-16 094227](https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/assets/34475380/f8e87599-7cf7-4b32-b153-c7d253b2c3ae)

**Comment by BertyDR** [comment]
I got the same issue with Godaddy:
lexicon: error: argument provider_name: invalid choice: 'null'

**Comment by troykelly** [comment]
@dxh000130 @BertyDR 
The example configuration is the complete yaml, so in the editor - either edit the yaml:
![Screenshot by Dropbox Capture](https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/assets/4564803/1788f48a-5393-4e36-9d3e-1ce262b35419)

or, just remove the "dns" key, ie

```yaml
provider: aliyun
aliyun_auth_key_id: SPECIFY ACCESS KEY ID FOR AUTHENTICATION
aliyun_auth_secret: SPECIFY ACCESS SECRET FOR AUTHENTICATION
```

**Comment by troykelly** [comment]
@dxh000130 @BertyDR 
The example configuration is the complete yaml, so in the editor - either edit the yaml:
![Screenshot by Dropbox Capture](https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/assets/4564803/1788f48a-5393-4e36-9d3e-1ce262b35419)

![Screenshot by Dropbox Capture](https://github.com/troykelly/hassio-addons-letsencrypt-lexicon/assets/4564803/9e8b6f0e-99da-4470-a867-9d7d362d7916)

or, just remove the "dns" key, ie

```yaml
  provider: aliyun
  aliyun_auth_key_id: SPECIFY ACCESS KEY ID FOR AUTHENTICATION
  aliyun_auth_secret: SPECIFY ACCESS SECRET FOR AUTHENTICATION
```
