### ISSUE TITLE
Any way to disable SSL verification

### ISSUE THREAD

**Issue by pablomarquesmendez** [troykelly/hassio-addons-letsencrypt-lexicon#43]
# Problem/Motivation

It does not work when a cert in the infoblox (and others maybe) server is a self signed cert. 

## Expected behavior

To succeed

## Actual behavior

I am getting 
requests.exceptions.SSLError: HTTPSConnectionPool(host='infoblox.example.com', port=443): Max retries exceeded with url: /wapi/v2.6.1/zone_auth?fqdn=example.com&view=default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
ERROR: deploy_challenge hook returned with non-zero exit code
[15:21:45] WARNING: certificate refresh crashed, halting add-on

## Steps to reproduce

Connect to a infoblox with a recent SSL or selfsigned certificate 

## Proposed changes

Can a checkSSL=False variable be implemented in the config ?

**Comment by troykelly** [comment]
Can you share the config (without tokens) that you are using?

**Comment by pablomarquesmendez** [comment]
> Can you share the config (without tokens) that you are using?

sure

```
email: pmarques@miamilinux.net
updatedelay: 100
domains:
  - ha.example.com
certfile: fullchain.pem
keyfile: privkey.pem
dns:
  provider: infoblox
  infoblox_auth_psw: password
  infoblox_auth_user: infobloxuser
  infoblox_ib_host: gridman.example.com
  infoblox_ib_view: External
```

Thank you
