### ISSUE TITLE
Issue with Godday

### ISSUE THREAD

**Issue by HAlover99** [troykelly/hassio-addons-letsencrypt-lexicon#9]
HI Troykelly

I have some problem to use your addon, because I don't understand if the CSR is generated from your addon or i need generate them before start it, so if need generate CSR before start addon what is the PATH where is copy these files?
Could you help me?

```
email: xxxxxxxx
domains:
  - home.xxxxx.com
certfile: fullchain.pem
keyfile: privkey.pem
dns:
  provider: godaddy
  godaddy_key: xxxxxxxxxxxxxx
  godaddy_secret: xxxxxxxxxxxxx
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:39:06] INFO: [home_xxxxx_com]:	home.xxxxx.com
[12:39:06] INFO: Requesting domains from LetsEncrypt
# Home Assistant Domains
home.xxxx.com > home_xxxxx_com
# END Home Assistant Domains
# INFO: Using main config file /etc/dehydrated/config
To use dehydrated with this certificate authority you have to agree to their terms of service which you can find here: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
To accept these terms of service run `/opt/dehydrated/dehydrated --register --accept-terms`.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
